### ISSUE TITLE
Possible repo upgrade options

### ISSUE THREAD

**Issue by mstopa** [I-Behdar/Cryptocurrency_Exchange#1]
Please consider the following to upgrade the project:

- add `README.md`, `setup.sh` and `setup.py` files. Please describe project setup and usage in readme.
- please change `data = parser()` to `args = `
- `output = conversion(amount=args.amount, crypto_currency=args.crypto_currency, normal_currency=args.currency)`
- `print(f"{fetch_symbol(data.crypto_currency)} {data.amount} = USD {output}")` - please change hardcoded USD to a variable for any requested currency
- Please update help messages in `parser.add_argument` calls

**Comment by I-Behdar** [comment]
Thanks Maczek, I implemented all the changes.

**Comment by mstopa** [comment]
Thank you, here are some further possible upgrade options:

- In `README.md` please make two sections: Setup and Usage. In setup please direct the user to run `setup.sh` (`setup.py` runs automatically within setup.sh through `pip install .`). In the usage please provide a code snippet with an example usage of your app.
- Please remove pandas from requirements and setup.py, it is not used in the code
- Please fix this bug:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
```

When ready please open a PR from `version-1` to main and please assign me to it

**Comment by mstopa** [comment]
Let's put it on hold for further discussion on the next call

**Comment by I-Behdar** [comment]
Done

**Comment by mstopa** [comment]
There are a few points to discuss on the call today but I believe that it's going to be the last round of review

**Comment by mstopa** [comment]
Closing this due to existing PR for further discussion https://github.com/I-Behdar/Cryptocurrency_Exchange/pull/2
